### PR TITLE
Converted to ARC

### PR DESCRIPTION
**Pull request by Air-Craft**

### CODE REVIEW

**Comment by domhofmann** [comment]
Thanks for your hard work. It turns out that we had another pending pull request for ARC, which was a little more thorough (it also updated the example project), so went with that one this time!

**Comment by QuinnFrederick** [comment]
No worries.  Thank you.  I'll pull that one...

**Comment by QuinnFrederick** [comment]
Ok.  It generates a compiler warning in Xcode 4.4.  Init'ing a=0 solves the problem.  Probably not worth a pull request for 6 character so I'll leave it to you... :)

**Comment by QuinnFrederick** [comment]
Great lib by the way.  I dropped it in my code and solved my custom tween problem within a minute!

**Pull request closed without merging**
